In [9]:
#Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.
#operations.
#è Product (prod)
#è Multiplication (multiply)
#è Dot Product (dot)
import numpy as np
matrix1=np.random.randint(10,size=(3,3))
matrix2=np.random.randint(10,size=(3,3))

print(matrix1)

print("\n" ,matrix2)
x=np.prod([matrix1,matrix2])
print("the product is",x)
y=np.multiply(matrix1,matrix2)
print("the multiplication is\n",y)
z=np.dot(matrix1,matrix2)
print("the dot product is\n",z)




[[6 0 7]
 [1 2 4]
 [6 3 2]]

 [[0 1 4]
 [3 8 2]
 [9 7 9]]
the product is 0
the multiplication is
 [[ 0  0 28]
 [ 3 16  8]
 [54 21 18]]
the dot product is
 [[63 55 87]
 [42 45 44]
 [27 44 48]]


In [14]:
#Q2. Perform the following set operations using the Numpy functions.
#è Union
#è Intersection
#è Set difference
#è XOR
import numpy as np
array1=np.array([3,4,5,6,7])
array2=np.array([8,9,7,6,6])

x=np.union1d(array1,array2)
print("union:",x)
y=np.intersect1d(array1,array2)
print("intersection:",y)
z=np.setdiff1d(array1,array2)
print("set difference:",z)
x1=np.setxor1d(array1,array2)
print("set xor:",x1)

union: [3 4 5 6 7 8 9]
intersection: [6 7]
set difference: [3 4 5]
set xor: [3 4 5 8 9]


In [18]:
#Q3. Create a 1D array using Random function and perform the following operations.
#è Cumulative sum
#è Cumulative Product
#è Discrete difference (with n=3)
#è Find the unique elements from the array
import numpy as np


array_size = 10
random_array = np.random.rand(array_size)

print("Original Array:")
print(random_array)

cumulative_sum = np.cumsum(random_array)
print("\nCumulative Sum:")
print(cumulative_sum)

cumulative_product = np.cumprod(random_array)
print("\nCumulative Product:")
print(cumulative_product)

n = 3
discrete_diff = np.diff(random_array, n=n)
print("\nDiscrete Difference with n=3:")
print(discrete_diff)


unique_elements = np.unique(random_array)
print("\nUnique Elements:")
print(unique_elements)


Original Array:
[0.14960211 0.85018036 0.02361294 0.63296141 0.27834329 0.28537306
 0.70119346 0.05272055 0.92995467 0.84717516]

Cumulative Sum:
[0.14960211 0.99978248 1.02339542 1.65635682 1.93470011 2.22007318
 2.92126663 2.97398718 3.90394186 4.75111702]

Cumulative Product:
[1.49602113e-01 1.27188779e-01 3.00330071e-03 1.90097344e-03
 5.29123201e-04 1.50997509e-04 1.05878465e-04 5.58197087e-06
 5.19097988e-06 4.39766923e-06]

Discrete Difference with n=3:
[ 2.96306158 -2.39988249  1.32561448  0.04714273 -1.47308392  2.59000033
 -2.48572066]

Unique Elements:
[0.02361294 0.05272055 0.14960211 0.27834329 0.28537306 0.63296141
 0.70119346 0.84717516 0.85018036 0.92995467]


In [19]:
#Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())
import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

result_zip = [sum(x) for x in zip(array1, array2)]


result_np_add = np.add(array1, array2)

def add_elements(x, y):
    return x + y

add_func = np.frompyfunc(add_elements, 2, 1)

result_user_defined = add_func(array1, array2)

# Print the results
print("Method 1 (Using zip()):")
print(result_zip)

print("\nMethod 2 (Using np.add()):")
print(result_np_add)

print("\nMethod 3 (Using np.frompyfunc() - User-defined function):")
print(result_user_defined)


Method 1 (Using zip()):
[7, 9, 11, 13, 15]

Method 2 (Using np.add()):
[ 7  9 11 13 15]

Method 3 (Using np.frompyfunc() - User-defined function):
[7 9 11 13 15]


In [20]:
#Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().
import numpy as np
from functools import reduce
import math


array = np.array([12, 18, 24, 30, 36])

def lcm(x, y):
    return x * y // math.gcd(x, y)

def gcd(x, y):
    return math.gcd(x, y)

lcm_result = reduce(lcm, array)

gcd_result = reduce(gcd, array)

print("Array:", array)
print("LCM:", lcm_result)
print("GCD:", gcd_result)


Array: [12 18 24 30 36]
LCM: 360
GCD: 6
